approval_policy = "never"           # 完全自動
sandbox_mode    = "workspace-write" # 読み書き可（ワークスペース内）

projects = { "/home/devuser/workspace" = { trust_level = "trusted" } }
model = "gpt-5"
model_provider = "openai"
model_reasoning_effort = "high"

[sandbox_workspace_write]
network_access = true               # ★ネット許可

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

# [mcp_servers.serena]
# command = "npx"
# args = ["-y", "mcp-remote", "http://localhost:9121/sse", "--transport", "sse-only", "--context", "codex"]
# 
# [mcp_servers.cognee]
# command = "sh"
# args = ["bin/run_cognee.sh"]
# 

