projects = { "/home/devuser/workspace" = { trust_level = "trusted" } }
model = "gpt-5"
model_provider = "openai"
model_reasoning_effort = "high"
approval_policy = "never"           # 完全自動
sandbox_mode    = "workspace-write" # 読み書き可（ワークスペース内）


[sandbox_workspace_write]
network_access = true               # ★ネット許可

[profiles.very-fast]
model_reasoning_effort = "minimal"

[profiles.fast]
model_reasoning_effort = "low"

[profiles.base]
model_reasoning_effort = "medium"

[profiles.deep]
model_reasoning_effort = "high"

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.serena]
command = "npx"
args = ["-y", "mcp-remote@latest", "http://serena:9121/sse", "--allow-http", "--transport", "sse-only", "--context", "codex"]

[mcp_servers.codex_mcp]
command = "codex"
args = ["mcp"]

# [mcp_servers.cognee]
# command = "sh"
# args = ["bin/run_cognee.sh"]


